### ISSUE TITLE
Hamburger doesn't work properly Safari on mac and on iOS 

### ISSUE THREAD

**Issue by luluhoc** [luukdv/hamburger-react#36] opened 2021-06-12 10:19 UTC
So in chrome it works flawlessly but on Safari, it is buggy and when clicked it makes half the items disappear and later whole hamburger is not visible.

**Comment by luukdv** [comment] 2021-06-12 11:39
I just checked https://hamburger-react.netlify.app on different versions of Safari, but I can't find any issues. Can you give some more explanation on how to reproduce your issue?

**Comment by luluhoc** [comment] 2021-06-13 19:37
so when the backdrop filter is applied to safari the burger doesn't work properly.

`
`
`
-webkit-backdrop-filter: saturate(180%) blur(20px);`
`

**Comment by luluhoc** [comment] 2021-06-13 19:46
https://user-images.githubusercontent.com/22813220/121820024-bd680580-cc90-11eb-8f3b-0d3a489cab04.mov

**Comment by luukdv** [comment] 2021-06-13 21:02
Can you share a link to something like Codepen / Codesandbox with a minimal reproducible example?

**Comment by luluhoc** [comment] 2021-06-13 21:27
> Can you share a link to something like Codepen / Codesandbox with a minimal reproducible example?

https://codesandbox.io/s/blissful-northcutt-z3lw5?file=/src/App.js

**Comment by luluhoc** [comment] 2021-06-14 12:42
> Can you share a link to something like Codepen / Codesandbox with a minimal reproducible example?

were you able to check it out?

**Comment by luukdv** [comment] 2021-06-20 08:09
Thanks for the link, looks like an issue in Safari with `-webkit-backdrop-filter` unfortunately. This also seems to happen when I replace the hamburger with a simple `div` that does a transform. Just wanted to emphasize as well that `hamburger-react` doesn't do anything "special" graphically, it's just a few `div`s with `transition` + `transform`.

You can circumvent the Safari issue by forcing it to create a separate layer:

```
<div style={{ willChange: 'transform' }}>
  <Hamburger />
</div>
```

**Comment by luukdv** [comment] 2021-06-25 04:53
@luluhoc I’m closing this one, let me know if you have any other questions!

**Closed by luukdv** 2021-06-25 04:53 UTC
